name: Publicando em ambiente de Dev
on: 
  push:
    branches:
      - dev

jobs: 
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Configurando credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-accesss-key: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS__SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

    - name: Publicando na AWS - dev
      run: npm install && npm run build:dev
